#!/usr/bin/env bash
# .claude/hooks/agnostic-purity-check.sh
#
# PostToolUse hook for Edit/Write/MultiEdit on PGE framework files.
# Detects syntactic purity violations (absolute root paths, hardcoded bash paths)
# that would break framework portability across projects.
#
# Semantic violations (project-specific names, application URL patterns,
# framework version hardcoding, production-state assumptions) are NOT detected
# here -- those are handled by .claude/agents/agnostic-auditor.md (LLM subagent).
#
# This hook is the cheap, deterministic, blocking first line of defence.
# Exit codes:
#   0 = pass (no violations, or out of scope)
#   2 = violation detected -- Claude Code surfaces the failure to orchestrator

set -e
set -o pipefail

# Read Claude Code hook input (JSON via stdin).
hook_input="$(cat || true)"
tool_name=$(printf '%s' "$hook_input" | jq -r '.tool_name // empty' 2>/dev/null || true)
file_path=$(printf '%s' "$hook_input" | jq -r '.tool_input.file_path // .tool_input.path // empty' 2>/dev/null || true)

# Out-of-scope tool -> skip.
case "$tool_name" in
  Edit|Write|MultiEdit) : ;;
  *) exit 0 ;;
esac

# Empty file_path -> nothing to audit.
[ -n "$file_path" ] || exit 0

# Scope filter: only PGE framework definition files.
# Use case patterns that match both absolute and relative forms.
case "$file_path" in
  */.claude/agents/*.md|*/.claude/skills/*.md|*/.claude/references/*.md|*/.claude/skills/*/references/*.md|*/.claude/skills/*/SKILL.md|*/CLAUDE.md|.claude/agents/*.md|.claude/skills/*.md|.claude/references/*.md|.claude/skills/*/references/*.md|.claude/skills/*/SKILL.md|CLAUDE.md)
    : # in scope
    ;;
  *)
    exit 0 # out of scope
    ;;
esac

# Self-doc exception: agnostic-auditor.md is the regulation document itself
# and must contain literal violation-example tokens (V1-V8 illustrations).
# Layer 0 hook (regex-based) cannot semantically distinguish "regulation
# example" from "norm hardcoded as canon" -- layer 1 LLM auditor handles
# that case via its self-consistency exception (see agnostic-auditor.md
# "基本原則" section item 4).
case "$file_path" in
  */.claude/agents/agnostic-auditor.md|.claude/agents/agnostic-auditor.md)
    exit 0
    ;;
esac

# PJ-level CLAUDE.md exemption (Phase Z3+):
#
# A CLAUDE.md is FW-level if it is a sibling of .claude/ (= workspace root).
# Other CLAUDE.md files (in sub-projects / SUT roots) are PJ-level and exempt
# -- they intentionally declare PJ-specific values (image / port / connection
# strings / paths) per the pge-runtime-config-spec.md convention.
#
# Heuristic: if the CLAUDE.md's containing directory has a .claude/ sibling,
# it's the FW root CLAUDE.md and should be audited. Otherwise it's a PJ-level
# CLAUDE.md and exempt.
case "$file_path" in
  */CLAUDE.md|CLAUDE.md)
    dir=$(dirname "$file_path")
    if [ ! -d "$dir/.claude" ]; then
      # Sub-directory CLAUDE.md without .claude/ sibling -> PJ-level -> exempt
      exit 0
    fi
    ;;
esac

# File must exist and be readable. If hook fires before file write completes
# in some race, skip rather than false-positive.
[ -f "$file_path" ] || exit 0
[ -r "$file_path" ] || exit 0

# Section-aware exemption: removed in Phase Z7+.
#
# Historically (Phase Z3-Z6), the workspace root CLAUDE.md hosted a
# "## PGE Parallel DB Runtime" YAML section with PJ-specific literals,
# and this hook skipped violations within that section. As of Phase Z7+,
# PJ-specific runtime config has been migrated to `<PJroot>/plan/pge-runtime-config.json`
# (generated by the `/pge-runtime-survey` Skill and consumed by the
# `/pge-sprint-cycle` workflow). No framework file should declare PJ literals;
# the audit runs uniformly across the whole file.
filter_exempt_section() { cat; }

violations_v1v2=""
violations_v6=""
violations_v8=""

# ---------------------------------------------------------------------------
# V1+V2: absolute root path / project root assumption.
#
# Detects paths like:
#   /workspace/...   /home/...   /Users/...   /var/...   /tmp/...
#   /private/...     /opt/...
#
# Allowlist: text inside backticks for symbolic prose use (e.g. `/plan/foo.md`
# meaning "project-root-relative plan/foo.md") is NOT detected here because
# layer 2 (LLM auditor) can semantically distinguish prose vs bash literal.
# Layer 0 only catches the unambiguous cases.
# ---------------------------------------------------------------------------
abs_pattern='\b/(workspace|home|Users|var|tmp|private|opt|usr|etc)/[A-Za-z0-9._-]'

# Pick raw absolute-path occurrences. The grep returns "<lineno>:<text>".
raw=$(grep -nE "$abs_pattern" "$file_path" 2>/dev/null || true)

if [ -n "$raw" ]; then
  # Filter: drop lines that look like prose mentions inside <!-- ... -->
  # (HTML comments) -- those are intentional documentation references.
  filtered=$(printf '%s\n' "$raw" | grep -vE '<!--.*-->' | filter_exempt_section || true)
  if [ -n "$filtered" ]; then
    violations_v1v2="$filtered"
  fi
fi

# ---------------------------------------------------------------------------
# V6: hardcoded absolute path in bash command lines.
#
# Detects bash command invocations that start with `cd|find|grep|jq|cat|ls`
# followed by an absolute path. These break when CWD differs from the dev
# environment's assumed project root.
# ---------------------------------------------------------------------------
bash_cmd_abs='(^|[[:space:]`>])(cd|find|grep|jq|cat|ls|head|tail|wc|awk|sed)[[:space:]]+/[a-z]+/'
raw6=$(grep -nE "$bash_cmd_abs" "$file_path" 2>/dev/null | filter_exempt_section || true)

if [ -n "$raw6" ]; then
  violations_v6="$raw6"
fi

# ---------------------------------------------------------------------------
# V8 (subset): obvious hardcoded SUT directory references in bash literal.
#
# We only catch the most blatant form: any `<repo-name>-<type>/...` (where
# <type> is app/service/api/web) appearing in bash command context. This is
# a narrow rule on purpose -- layer 2 LLM handles the broader semantic case.
# ---------------------------------------------------------------------------
sut_pattern='(^|[[:space:]`>])(cd|find|grep|jq|cat|ls)[[:space:]]+[A-Za-z0-9_-]+-(app|service|api|web)/[A-Za-z0-9._/-]'
raw8=$(grep -nE "$sut_pattern" "$file_path" 2>/dev/null | filter_exempt_section || true)
if [ -n "$raw8" ]; then
  violations_v8="$raw8"
fi

# ---------------------------------------------------------------------------
# Emit results.
# ---------------------------------------------------------------------------
if [ -z "$violations_v1v2" ] && [ -z "$violations_v6" ] && [ -z "$violations_v8" ]; then
  exit 0
fi

{
  printf '=== agnostic-purity-check: violations in %s ===\n' "$file_path"
  if [ -n "$violations_v1v2" ]; then
    printf '\n[V1/V2] absolute root path / project root assumption:\n'
    printf '%s\n' "$violations_v1v2"
  fi
  if [ -n "$violations_v6" ]; then
    printf '\n[V6] hardcoded absolute path in bash command:\n'
    printf '%s\n' "$violations_v6"
  fi
  if [ -n "$violations_v8" ]; then
    printf '\n[V8] hardcoded SUT directory in bash command:\n'
    printf '%s\n' "$violations_v8"
  fi
  printf '\nFIX:\n'
  printf '  - Replace absolute paths with CWD-relative form (plan/..., e2e/..., src/...).\n'
  printf '  - Move project-specific data into TI artifacts (route_map.json, aria_snapshot.yaml).\n'
  printf '  - For semantic violations (project-specific names, URL patterns, FQCN), run\n'
  printf '    the agnostic-auditor subagent (see .claude/agents/agnostic-auditor.md).\n'
} >&2

exit 2
